### PR TITLE
chore(pagerduty)

### PR DESCRIPTION
**Pull request by kaustavha**
Rejig pagerduty util to use an auth token in lieu of a username and password

connected to https://github.com/racker/dreadnot/pull/95

### CODE REVIEW

**Comment by drenalin23** [comment]
LGTM +1

**Comment by kaustavha** [comment]
This PR is on hold till we edit the api_key object in our chef data bags. 
Assigned to @drenalin23 and @mburns

**Comment by mburns** [comment]
Merging this PR, so that the [Chef PR](https://github.com/racker/chef/pull/3097) can update the data_bag && bump the [revision to download](https://github.com/racker/chef/blob/master/site-cookbooks/dreadnot/recipes/default.rb#L97-L107).

**Comment by mburns** [comment]
:+1:

**Pull request merged**
